### ISSUE TITLE
TypeScript migration

### ISSUE THREAD

**Issue by dirkdev98** [compasjs/compas#3198]
```[tasklist]
### Tasks
- [ ] Author all Compas code in TypeScript
- [x] Add TypeScript generators for router, database, validators, etc
- [ ] Figure out a compatiblity story for `compas test`
- [ ] Figure out a compat story for `compas migrate` (settings + JS migration files)
- [ ] Attempt a code-mod to execute the migration on a commony structured code base
```

**Comment by dirkdev98** [comment]
See https://github.com/lightbasenl/platforms/tree/7f6879cba6527bc8b26572be88dc62c90b04f426/packages/compas-convert for a migration tool.
