### ISSUE TITLE
Drop eslint-plugin -> migrate to @lightbase/eslint-config

### ISSUE THREAD

**Issue by dirkdev98** [compasjs/compas#3199]
```[tasklist]
### Tasks
- [x] Add some form of support in `compas lint`. This keeps the muscle memory alive for a bit
- [x] Migrate this repo over
- [x] Deprecate the package on NPM
```
